//------------------------------------------------------------------------------
// <auto-generated>
//    此代码是根据模板生成的。
//
//    手动更改此文件可能会导致应用程序中发生异常行为。
//    如果重新生成代码，则将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace SelCourse
{
    using System;
    using System.Collections.Generic;
    
    public partial class StudentInfo
    {
        public int StuId { get; set; }
        public string StuName { get; set; }
        public string StuSex { get; set; }
        public Nullable<int> StuAge { get; set; }
        public string Profession { get; set; }
        public Nullable<int> IsAdmin { get; set; }
        public string StuIphone { get; set; }
        public string StuQq { get; set; }
        public string Remark { get; set; }
        public string Password { get; set; }
    }
}
